# Generated by Django 5.0.1 on 2024-01-06 13:18

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageName', models.CharField(max_length=50)),
                ('mainImage', models.FileField(upload_to='imagesFolder/')),
                ('category', models.CharField(max_length=50)),
                ('imageSlug', autoslug.fields.AutoSlugField(editable=False, populate_from='imageName', unique=True)),
            ],
        ),
    ]
